#!/bin/sh

# @(#)pmcanon	1.6 (PGP Moose) 95/12/29
# Canonicalisation script for PGP Moose
# (in other words, it takes a news article and turns it
# into something we can compute/check a signature on.)
# Written by Greg Rose, RoSecure Software, Copyright C 1995.

# Be neat and tidy.
TMP=/tmp
TF=$TMP/pgpmt$$
trap "rm -f /$TF.?" 0 1 2 3 15

# Check usage. File must be specified, and result comes out on stdout.
if [ $# = 0 ]; then
    cat >$TF.f
    FILE=$TF.f
elif [ $# != 1 -o ! -f "$1" ]; then
    echo >&2 "usage: $0 article"
    exit 1
else
    FILE=$1
fi

# multiple greps so we can guarantee order
pmnewsgroups $FILE
{
    grep -i "^From:" "$FILE"
    grep -i "^Subject:" "$FILE"
    grep -i "^Message-ID:" "$FILE"
} | sed -e 's/^[^:]*: *//' -e 's/: */:/g' -e 's/[ 	]*$//'
sed -e '1,/^ *$/d' \
    -e '/^ *$/d' \
    -e 's/^--/- --/' \
    -e 's/^[Ff][Rr][Oo][Mm]/>&/' \
    -e 's/^[Ss][Uu][Bb][Jj][Ee][Cc][Tt]/>&/' \
    -e 's/^\.$/../' \
    -e 's/[ 	]*$//' \
    "$FILE"
